config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
root 'welcome#index'
  resources :projetos

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Cadastro realizado com sucesso !!' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Cadastro atualizado' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Cadastro deletado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nome, :matricula, :endereco, :telefone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_area :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editing Projeto</h1>

<%= render 'form' %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>
<style>
table {
    border-collapse: collapse;
    width: 100%;
    font-size:16px;
}

th, td {
    text-align: center;
    padding: 8px;
    font-size: 16px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>


<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= projeto.nome %></td>
        <td><%= projeto.matricula %></td>
        <td><%= projeto.endereco %></td>
        <td><%= projeto.telefone %></td>
        <td><%= link_to 'Mostrar', projeto %></td>
        <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Deletar', projeto, method: :delete, data: { confirm: 'Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to 'Cadastrar Novo', new_projeto_path %></h2>

app/views/projetos/new.html.erb
<h1>Cadastrar</h1>

<%= render 'form' %>
<br>
<h2><%= link_to 'Voltar', projetos_path %></h2>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>
<style>
table, td, th {    
    border: 1px solid #ddd;
    text-align: left;
}

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}

th {
    background-color: #4CAF50;
    color: white;
}

</style>


<table>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Endereco</th>
      <th>Telefone</th>
     
    </tr>
 

      <tr>
        <td><%= @projeto.nome %></td>
        <td> <%= @projeto.matricula %></td>
        <td> <%= @projeto.endereco %></td>
        <td> <%= @projeto.telefone %></td>
      </tr>
</table>


<br><br>
<h2><%= link_to 'Editar', edit_projeto_path(@projeto) %> |
<%= link_to 'Voltar', projetos_path %></h2>

app/views/welcome/index.html.erb
<center><h1><%= link_to 'CRUD Rails', projetos_path %></h1></center>